# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  test-job:
    working_directory: ~/hello
    docker:
      - image: circleci/node:12.11.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install node_modules
          command: npm install
      - run:
          name: Test
          command: ./node_modules/.bin/ng test --code-coverage --single-run

  deploy-job:
       docker:
         - image: circleci/node:12.11.1
       working_directory: ~/repo
       steps:
         - restore_cache:
             keys:
              - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
         - run:
             name: show directory
             command: pwd
         - run:
             name: Install node_modules
             command: npm install
         - run:
             name: Install node_modules
             command: ./node_modules/.bin/ng add angular-cli-ghpages
         - run:
             name: Deploy Master to Firebase
             command: ./node_modules/.bin/ng deploy --base-href=./

workflows:
  version: 2

  -test:
    jobs:
      - test-job

  -deploy:
    jobs:
      - deploy-job:
          filters:
            branches:
              only: master
